spring:
  application:
    name: projeto-turismo
  
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/turismo_db
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  
  # MongoDB (local)
  data:
    mongodb:
      host: localhost
      port: 27017
      database: turismo_db
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

  app:
  upload:
    dir: uploads  # Pasta onde as fotos ser√£o salvas